export const IMG_CDN_URL =
  'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/';
export const REST_MENU_URL =
  'https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=28.7040592&lng=77.10249019999999&restaurantId=';
//swiggy api https://www.swiggy.com/dapi/restaurants/list/v5?lat=30.3164945&lng=78.03219179999999&is-seo-homepage-enabled=true&page_type=
export const RestaurantList = [
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '657142',
        name: 'Punjabi Angithi (Delhi Wale)',
        uuid: '269728de-0f94-4ea2-a78a-63f28ff53347',
        city: '22',
        area: 'Hathibarkala',
        totalRatingsString: '',
        cloudinaryImageId: '0a59d45ca92d85e5f63f5bc79f3dbb33',
        cuisines: ['North Indian', 'Chinese', 'Punjabi', 'Kebabs', 'Tandoor'],
        tags: [],
        costForTwo: 40000,
        costForTwoString: '₹400 FOR TWO',
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: '28 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: 'punjabi-angithi-hathibarkala-hathibarkala',
          city: 'Dehradun',
        },
        cityState: '22',
        address: '',
        locality: 'Rajpur Road',
        parentId: 4464,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 2400,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 2400,
          message: '',
          title: 'Delivery Charge',
          amount: '2400',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=7666597~p=1~eid=00000189-cf36-63f8-1b5c-9b6100ba010f~srvts=1691398595576~83645',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '4.6 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=657142&source=collection&query=North%20Indian',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 0,
          lastMileDistance: 4.6,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '4.1',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '371422',
        name: 'Handi punjab ki',
        uuid: '411ddff7-3572-4a8d-a2ec-12971958f5b0',
        city: '22',
        area: 'Hathibarkala Salwala',
        totalRatingsString: '',
        cloudinaryImageId: 'vozwrqdkvfcfutehx4ld',
        cuisines: ['North Indian', 'Chinese', 'Tandoor'],
        tags: [],
        costForTwo: 25000,
        costForTwoString: '₹250 FOR TWO',
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: '29 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: 'handi-punjab-ki-hathibarkala-hathibarkala',
          city: 'Dehradun',
        },
        cityState: '22',
        address: '',
        locality: 'Rajpur Road',
        parentId: 93115,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 2400,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 2400,
          message: '',
          title: 'Delivery Charge',
          amount: '2400',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=7813503~p=2~eid=00000189-cf36-63f8-1b5c-9b6200ba022a~srvts=1691398595576~83645',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '4.2 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=371422&source=collection&query=North%20Indian',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 0,
          lastMileDistance: 4.2,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '4.1',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '69584',
        name: 'New Tuhada Dhaba',
        uuid: '5d163690-e878-4ac7-a173-295a7e02ce4b',
        city: '22',
        area: 'Chukkuwala',
        totalRatingsString: '',
        cloudinaryImageId: 'yxejr2d0pjnuhegcicst',
        cuisines: ['Punjabi', 'Indian', 'Desserts'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: '24 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: 'tuhada-dhaba-chukkuwala-chukkuwala',
          city: 'Dehradun',
        },
        cityState: '22',
        address: '',
        locality: 'Rajpur Road',
        parentId: 15790,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 1900,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 1900,
          message: '',
          title: 'Delivery Charge',
          amount: '1900',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '2.6 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=69584&source=collection&query=North%20Indian',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 0,
          lastMileDistance: 2.6,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.5',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '206939',
        name: "Chilli'Z Restro Express",
        uuid: 'b2dcf4e5-cfa6-4555-acbe-ff19f2303b32',
        city: '22',
        area: 'Dharampur',
        totalRatingsString: '',
        cloudinaryImageId: 'wo5zg4yicxrhuzwb0tad',
        cuisines: ['Chinese', 'North Indian'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: '22 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: "chilli'z-restro-express-dharampur-dharampur",
          city: 'Dehradun',
        },
        cityState: '22',
        address: '',
        locality: 'Old Nehru Colony',
        parentId: 13394,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 1900,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 1900,
          message: '',
          title: 'Delivery Charge',
          amount: '1900',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '2.8 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=206939&source=collection&query=North%20Indian',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 0,
          lastMileDistance: 2.8,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.8',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '367799',
        name: 'Shree Gopal Ji Ki Hatti',
        uuid: 'b32a424f-8032-4d6a-bbb6-223f8e2a7f3d',
        city: '22',
        area: 'Paltan Bazaar',
        totalRatingsString: '',
        cloudinaryImageId: '504930a5d8c91a7a2ccaa74f9bff3874',
        cuisines: ['North Indian', 'Beverages'],
        tags: [],
        costForTwo: 15000,
        costForTwoString: '₹150 FOR TWO',
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: '29 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: 'shree-gopalji-ki-hatti-hathibarkala-hathibarkala',
          city: 'Dehradun',
        },
        cityState: '22',
        address: '',
        locality: 'Darshan Lal Chowk',
        parentId: 184642,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 1900,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 1900,
          message: '',
          title: 'Delivery Charge',
          amount: '1900',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '1.5 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=367799&source=collection&query=North%20Indian',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 0,
          lastMileDistance: 1.5,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.2',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '408570',
        name: 'Dhaba Singh Darbar',
        uuid: 'ea9ae3b0-6b1f-4e23-a8ed-537af4bf5a11',
        city: '22',
        area: 'Prem Nagar',
        totalRatingsString: '',
        cloudinaryImageId: 'ckvrraxwm26x9uzpbfvd',
        cuisines: ['North Indian', 'Chinese', 'Snacks', 'Sweets'],
        tags: [],
        costForTwo: 25000,
        costForTwoString: '₹250 FOR TWO',
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: '39 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: 'singh-darbar-prem-nagar-prem-nagar',
          city: 'Dehradun',
        },
        cityState: '22',
        address: '',
        locality: 'Kehri Gaon',
        parentId: 188420,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 5200,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 5200,
          message: '',
          title: 'Delivery Charge',
          amount: '5200',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '8.8 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=408570&source=collection&query=North%20Indian',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 0,
          lastMileDistance: 8.8,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.8',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
  {
    cardType: 'restaurant',
    layoutAlignmentType: 'VERTICAL',
    data: {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '254751',
        name: 'Anandam',
        uuid: 'c70c8586-0584-48d4-acc1-ffeddfd4a262',
        city: '22',
        area: 'Patel Nagar',
        totalRatingsString: '',
        cloudinaryImageId: 'i9sujiwnyj7nqclrlv6y',
        cuisines: ['North Indian', 'South Indian', 'Sweets', 'Snacks'],
        tags: [],
        costForTwo: 30000,
        costForTwoString: '₹300 FOR TWO',
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        slaString: '21 MINS',
        lastMileTravel: 0,
        slugs: {
          restaurant: 'anandam-malsi-malsi',
          city: 'Dehradun',
        },
        cityState: '22',
        address: '',
        locality: 'Niranjanpur',
        parentId: 2649,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: 'BASE_DISTANCE',
              fee: 1900,
              message: '',
            },
            {
              name: 'BASE_TIME',
              fee: 0,
              message: '',
            },
            {
              name: 'ANCILLARY_SURGE_FEE',
              fee: 0,
              message: '',
            },
          ],
          totalFees: 1900,
          message: '',
          title: 'Delivery Charge',
          amount: '1900',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '2.5 kms',
        hasSurge: false,
        cta: {
          link: 'swiggy://menu?restaurant_id=254751&source=collection&query=North%20Indian',
          type: 'DEEPLINK',
          text: 'RESTAURANT_MENU',
        },
        sla: {
          restaurantId: '',
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          lastMileTravel: 0,
          lastMileDistance: 2.5,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.1',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    parentWidget: false,
  },
];
